### ISSUE TITLE
Traceback error when RunCMVS.py

### ISSUE THREAD

**Issue by HaiDang2001VN** [pmoulon/osm-bundler#15]
I began with ET examples which provided with the osm-bundler archive for Windows. I tested it with `Win64` osm-bundler.
After I run, the RunBundler.py successfully, it created the folder in `"Local/Temp/osm-bundler-whs2_u"` as predicted. But when I run `RunCMVS.py --bundlerOutputPath=".../osm-bundler-whs2_u"  --ClusterToCompute="10"` but it exited with error:
`Traceback (most recent call last):
  File "D:\HAIDANG\PTNK\Tin\Computer Vision\Photogrammetry\osm-bundler\osm-bundlerWin64\RunCMVS.py", line 13, in <module>
    manager.doCMVS()
  File "D:\HAIDANG\PTNK\Tin\Computer Vision\Photogrammetry\osm-bundler\osm-bundlerWin64\osmcmvs\__init__.py", line 111, in doCMVS
    os.chdir(os.path.join(self.workDir,"pmvs"))
WindowsError: [Error 2] The system cannot find the file specified: 'C:\\Users\\User\\AppData\\Local\\Temp\\osm-bundler-whs2_u\\bundle\\pmvs'`
Could you please guide me to fix it if the error came from my use of code, @pmoulon ?
Thanks you in advance.

**Comment by HaiDang2001VN** [comment]
Oh, I saw that you have just commented to line 10 in RunCMVS.py:
`manager.doBundle2PMVS()`
I think that you just avoid it from infinite loop, because after that, I tried with `--ClusterToCompute="4"` and it was print 0 matrix over and over Cmd.
But when I tried it with some number >=4 then it succeeded, I thought.
So it now can run with some settings of Input parameters.
Can you please explain for me how it failed with that ClusterToCompute parameter, @pmoulon ?
Thanks in advance.

**Comment by pmoulon** [comment]
I would advise you to use more recent project like OpenMVG https://github.com/openMVG/openMVG
